# version: "3.8"
services:
  db:
    image: "postgres:16-alpine"
    container_name: "urlDB"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dev_sincero
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: url_de_short
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
  cache:
    image: redis:7-alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
    restart: always
volumes:
  postgres_data:
